export const STRINGS = {
  TRIA: 'tria',
  GET_STARTED: 'Get started',
  TAGLINE: `One name,\nall things Web3`,
  EXPERIENCE_OMNI: 'Experience Omni-Presence',
  CONTINUE_AS_GUEST: 'Continue as Guest',
  EXPERIENCE_SPEED: 'Experience the speed with',
  QUICK_EASY: 'Quick and Easy Setup',
  LOGIN: 'Log in',
  SIGNUP: 'Sign up with Tria',
  CONTINUE_WITH: 'Continue with',
  GOOGLE: 'Google',
  APPLE: 'Apple',
  EMAIL_PHONE: 'Email/ Phone',
  OTHERS: 'Others',
  CREATE_TRIA_NAME: 'Create Tria name',
  CREATE_TRIA_SUBTITLE: 'your username to web3',
  USERNAME_AVAILIABLE:"username available",
  USERNAME_UNAVAILIABLE:"username unavailable",
  FREE:"Free",
  TAPPING_ON_NEXT:"Tapping on next, you agree to our T&C.",
  NEXT:"Next",
  ENTER_USERNAME:"Enter username",
  CREATE_PASSWORD:"Create Password",
  PASSWORD_SUBHEADING:"protect your account",
  SECURE_YOUR_WALLET:"Secure your Wallet",
  PASSWORD_VALIDATION:"We recommend using alphanumeric text and special characters for stronger passwords",
  PASSWORD_CONFIRMATION:"Please confirm your password...",
  PASSWORD_ERROR:"Um.. This won't work!",
  PERFECTLY_MATCHED:"Perfectly matched!",
  PASSWORD_UNMATCH:"Password does not match!",
  PASSWORD_BETTER:"Better, but we want the best!",
  PASSWORD_STRONG:"Super strong password!",
  PASSWORD_PLACEHOLDER:"Enter Password..."


};

